
name: MyFirstAction

on:  
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  first_build:
    runs-on: ubuntu-latest
 

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Print Hello World
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
    
  secoun_build:
    runs-on: ubuntu-latest
    steps:
      - name: ls -la
        run: ls -la   
  
     


