
name: MyFirstAction

on:  
  push:
    branches: [ master ]


jobs:
  first_build:
    runs-on: ubuntu-latest
 

    steps:
      - name: Print Hello World
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
            
  secoun_build:
    runs-on: ubuntu-latest
    
    steps:
      - name: ls -la
        run: ls -la
        
      - name: check python
        run: python --version
        
      - name: check appaceh
        run: appache --version      
  
     


